branches:
  only: 
    - next
matrix:
  include:
    - stage: "Build next"
      os: linux
      env: 
        - BuildAndroid="28"
      language: android
      jdk: oraclejdk8
      before_install: nvm install 10
      script:
        - cd src
        - npm run postclone gitHubUsername=TheGitHubUser pluginName=ThePlugin initGit=y includeTypescriptDemo=y includeAngularDemo=n && npm run tsc && cd ../demo
        - npm install tns-core-modules@next -P --save-exact
        - npm install tns-platform-declarations@next -D --save-exact
        - npm install nativescript-dev-webpack@next -D --save-exact 
        - ./node_modules/.bin/update-ns-webpack --deps --configs
        - npx rimraf -- hooks node_modules platforms package-lock.json
        - tns platform add android@next
        - travis_wait travis_retry tns build android
    - os: osx
      env: 
        - BuildiOS="12.0"
        - Xcode="10.0"
      osx_image: xcode10.0
      language: node_js 
      node_js: "10"
      jdk: oraclejdk8
      script:
        - cd src
        - npm run postclone gitHubUsername=TheGitHubUser pluginName=ThePlugin initGit=y includeTypescriptDemo=y includeAngularDemo=n && npm run tsc && cd ../demo
        - npm install tns-core-modules@next -P --save-exact
        - npm install tns-platform-declarations@next -D --save-exact
        - npm install nativescript-dev-webpack@next -D --save-exact 
        - ./node_modules/.bin/update-ns-webpack --deps --configs
        - npx rimraf -- hooks node_modules platforms package-lock.json
        - tns platform add ios@next
        - travis_wait travis_retry tns build ios
    - os: linux
      language: android
      env:
        - TestVersion="next"
      jdk: oraclejdk8
      before_install:
        - nvm install 10
      before_script:
        - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
        - cd seed-tests && npm i
      script: travis_wait travis_retry npm run test.android
    - os: osx
      env:
        - TestVersion="next"
      language: node_js
      node_js: "10"
      jdk: oraclejdk8
      osx_image: xcode10.0
      before_script:
        - cd seed-tests && npm i
      script: travis_wait travis_retry npm run test.ios

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-21
    - android-28
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_install:
    - sudo pip install --upgrade pip
    - sudo pip install six

install:
    - echo no | npm install -g nativescript@next
    - tns usage-reporting disable
    - tns error-reporting disable
    
